version: "3.8"

services:
  wordpress:
    image: wp-wordpress:5.8.1
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    container_name: wp-wordpress
    labels:
      name: "wp-wordpress"
    depends_on:
      - mysql
    volumes:
      - ../build/wp-content/:/var/www/html/wp-content/
    ports:
      - "8888:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DEBUG: 0
      WORDPRESS_ENV: development

  mysql:
    image: wp-mysql:8.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: wp-mysql
    labels:
      name: "wp-mysql"
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress

  node:
    image: wp-node:14
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: wp-node
    labels:
      name: "wp-node"
    ports:
      - "8080:8080"

  composer:
    image: wp-composer:2.1.11
    build:
      context: .
      dockerfile: Dockerfile.composer
    container_name: wp-composer
    labels:
      name: "wp-composer"

volumes:
  mysql_db: {}
